"""empty message

Revision ID: 87247a981dfa
Revises: 
Create Date: 2019-06-29 22:51:48.060343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87247a981dfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solarpanels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('efficiency_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solarpanels')
    # ### end Alembic commands ###
